### ISSUE TITLE
Not buying

### ISSUE THREAD

**Issue by copypasteearth** [SreekVed/Algo-Trader#1]
Hi,
I am using your program(just started it today)

It says 0 trades today I'm running it every half hour, and your heroku version says yours made 18 trades so far today. I was just wondering if any of your trades were buys because mine says 0 trades. Maybe it's just a bad day for nasdaq 100

Thanks.

**Comment by copypasteearth** [comment]
Also, how do you run yours with a Cron job? I changed it to loop and sleep.

**Comment by SreekVed** [comment]
Yeah, I am getting both buy and sell orders on Alpaca. I run every hour using Heroku Scheduler.

**Comment by copypasteearth** [comment]
Do I need a premium fin hub, or will it work with the free plan, I'm using the free plan and it's not buying

**Comment by SreekVed** [comment]
I'm using the free plan. I'm pretty sure the finnhub.aggregate_indicator() is the culprit - My code here is an older version which uses the aggregate "signal" field in the indicator which they don't calculate anymore. I changed it since to execute orders if the buy signal counts exceed the sells, and vice versa.

**Comment by copypasteearth** [comment]
Ahh, thanks so much I'll make those changes and update.

**Comment by copypasteearth** [comment]
its working now that i switched it to the count of buy and sell.  Thank you so much for clearing that up for me!!

**Comment by copypasteearth** [comment]
Are you using the neutral count, or just the buy and sell counts?

**Comment by SreekVed** [comment]
I'm not using the neutral counts.

**Comment by copypasteearth** [comment]
Ok, thanks, I just wanted to make sure

**Comment by copypasteearth** [comment]
finnhub stopped the free aggregate data!!!!
